### ISSUE TITLE
Is there a way to disable this?

### ISSUE THREAD

**Issue by wooziwoozi** [Darkroman/FrozenCookies#3]
![2019-11-30 - Screencap 001](https://user-images.githubusercontent.com/13823693/69902540-f960a180-135c-11ea-90ef-6a0065bcf93e.png)

I don't like how it looks, nor do I use it.

**Comment by luca4389** [comment]
any news about this? i want to remove this too

**Comment by RobertBuchananWMG** [comment]
I'm not finding it in this fork.  Found it in a different fork of the same, though:
https://github.com/Mtarnuhal/FrozenCookies
