### ISSUE TITLE
Halloween Cookies and Pledging

### ISSUE THREAD

**Issue by RobertBuchananWMG** [Darkroman/FrozenCookies#4]
I've noticed some contradictory behavior:

The AI is pledging after switching to Halloween to get the Halloween Cookies.

This is problematic, as you only get Halloween cookies from popping wrinklers, and Pledging prevents them from spawning. So it keeps spending more & more cookies on season switching to Halloween, and takes basically forever to get all the halloween cookies because it keeps pledging.

How hard would it be to add an escape to prevent pledging when you've season-switched to halloween and still have halloween cookies to get to ignore pledging? Or perhaps better: A switch to stop the Grandmapocolypse after Awoken stage, so pledging isn't needed?

**Comment by Darkroman** [comment]
Turn Grandmapocalypse mode on under blacklists, that should stop the pledging.
