### ISSUE TITLE
Autobuy no longer turns back on after Auto FTHOF Combo

### ISSUE THREAD

**Issue by paisthereason** [Darkroman/FrozenCookies#5]
I've read in the readme that Auto FTHOF Combo turns autobuy off when it triggers and turns it back on after it's done, which makes sense since there is selling wizard towers involved. However, since at least the most recent version, it no longer turns Autobuy back on after the combo triggers for me. This setting had never worked for me up until about June or so of 2020, then it worked until about November, and now it no longer works.

Are there any other recommended settings that I need to set that cause Auto FTHOF not to work unless they are set a certain way? Current settings are attached that cause Autobuy not to turn back on after Auto FTHOF.

![FCsettings](https://user-images.githubusercontent.com/5115871/107713724-dee0c280-6c99-11eb-9252-b5f9c851bb7b.png)

**Comment by mrbobdobolina** [comment]
I was experiencing similar issues, and now the issues have stopped... but I can't tell what, if anything changed.

**Comment by paisthereason** [comment]
Interesting.. I've had it turned off pretty much since I posted this, only trying it again occasionally to see if it would miraculously work, but it never did. I will give it another try..

**Comment by mrbobdobolina** [comment]
Something still seems off though. I'm not getting the big gains I was getting a while back, but I'm not sure what changed. The FTHOF Next Spell doesn't seem to be predicting the correct effect? IDK. Took maybe 2 or 3 weeks to bake 845 novemdecillion cookies and now it's been another 6 weeks and I'm only at 877 novemdecillion. Not sure if that's normal.

**Comment by prtlnd** [comment]
You are still able to run Frozen Cookies?

**Comment by Darkroman** [comment]
Hey sorry for not replying to this in a long time, been a while since I've played Cookie Clicker or even looked at my fork. So, interestingly I ran into an issue that for some reason, the chime being on only didn't change the outcome of the next spell. Further testing will be involved. Also regarding autobuy not turning back on, what browser are you using? It works fine for me in Chrome. This also requires additional testing (I haven't used your exact settings, but my hypothesis is it may have something to do with autoclicks being set at 250, which isn't even necessary as the game won't process more than 25-30 autoclicks at a time). I'll look more into it though when I get some time!

**Comment by Darkroman** [comment]
So after some testing it seems Chime being on or off doesn't affect the spell outcome anymore. I will update. As far as AutoFTHOFCombo not setting autobuy back on, still need to look into it.

**Comment by paisthereason** [comment]
Hey no worries, thanks for the reply! I am using Brave browser which is a chromium fork, but I haven't went back and just tried it on regular Chrome in a long time. I can import a save and try though if you'd like? I will also turn down the clicks too in my instance in Brave to see if that helps as well.

**Comment by Darkroman** [comment]
Go for it

**Comment by paisthereason** [comment]
So I've been running Cookie Clicker in Chrome for a bit, turned the clicks down ot 40/sec, and AutoFTHOF is still not turning Autobuy back on for me after it triggers. At first I thought it might've been some plug-in I had installed, but I have almost no plug-ins installed in my Chrome except for uBlock Origin. Are there any logs or anything I would be able to provide to you that would helpful?

**Comment by Darkroman** [comment]
So weird you're having that issue, but I switched up the syntax of the logic a little which in all honesty shouldn't make any difference, but it's been updated. Try it out and let me know.

**Comment by paisthereason** [comment]
It's been a while, but this does seem to be fixed. I'm running it Brave Browser again (it's chromium based) and I don't ever see autobuy turned off anymore.

What I've noticed now though is that Auto FTHOF doesn't seem to trigger if the monitor is off/turns off after inactivity. Do you know if that is by design/to be expected?
