### ISSUE TITLE
Use with beta v. 2.045?

### ISSUE THREAD

**Issue by mrbobdobolina** [Darkroman/FrozenCookies#8]
I've been hesitant to post this, because it's about the beta version of Cookie Clicker, but I've found that I get two Uncaught TypeErrors: which cause the page to freeze when trying to load this with the beta. Still seems to work fine with the production version.

`Uncaught TypeError: Game.UpgradesById.map is not a function
    upgradeStats https://darkroman.github.io/FrozenCookies//fc_main.js?_=1648090755823:2081
    recommendationList https://darkroman.github.io/FrozenCookies//fc_main.js?_=1648090755823:1933
    nextPurchase https://darkroman.github.io/FrozenCookies//fc_main.js?_=1648090755823:2006
    setOverrides https://darkroman.github.io/FrozenCookies//fc_main.js?_=1648090755823:117
    loadScript https://darkroman.github.io/FrozenCookies/frozen_cookies.js:45
    loadScript https://darkroman.github.io/FrozenCookies/frozen_cookies.js:51
    jQuery 6
[fc_main.js:2081:59](https://darkroman.github.io/FrozenCookies//fc_main.js?_=1648090755823)

Uncaught TypeError: nextChainedPurchase() is undefined
    delayAmount https://darkroman.github.io/FrozenCookies//fc_main.js?_=1648090755823:1885
    updateTimers https://darkroman.github.io/FrozenCookies//fc_button.js?_=1648090755824:260
    DrawBackground https://darkroman.github.io/FrozenCookies//fc_main.js?_=1648090755823:114
    Draw https://orteil.dashnet.org/cookieclicker/beta/main.js?v=2.095:15501
    Loop https://orteil.dashnet.org/cookieclicker/beta/main.js?v=2.095:15659`

**Comment by paisthereason** [comment]
v2.048 is officially out as of yesterday, which also breaks Frozen Cookies. Any plans to update Frozen Cookies darkroman?

**Comment by Darkroman** [comment]
At some point I will do a port of the newest official FC with my added functions, but probably not anytime soon. For now though you can check out this port https://github.com/erbkaiser/FrozenCookies . He's using my auto combos in his port and is a working FC.
